apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: elastic
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush     1
        Log_Level info

    [INPUT]
        Name        tail
        Path        /var/log/*.log
        Refresh_Interval 5

    [INPUT]
        Name        tail
        Path        /var/lib/docker/containers/*/*-json.log
        Refresh_Interval 5

    [FILTER]
        Name modify
        Match *
        Rename timestamp @timestamp
        Add source k8s-fluent-bit

    [OUTPUT]
        Name kafka
        Match *
        brokers broker:29092
        topics filebeat-logs
        format json